[package]
categories = ["compilers", "algorithms", "multimedia", "parser-implementations"]
description = "A stack-based array programming language"
documentation = "https://docs.rs/uiua"
edition = "2021"
keywords = ["uiua", "array", "stack", "language", "apl"]
license = "MIT"
name = "uiua"
readme = "readme.md"
repository = "https://github.com/uiua-lang/uiua"
rust-version = "1.82.0"
version = "0.15.0-dev.2"

[dependencies]
# Core dependencies
bitflags = {version = "2"}
bytemuck = {version = "1.17", features = ["must_cast", "derive", "extern_crate_alloc"]}
ctor = "0.3.6"
ecow = {version = "0.2.3"}
enum-iterator = "2.0.0"
indexmap = {version = "2"}
paste = "1.0.14"
pathdiff = "0.2.1"
time = {version = "0.3.36", features = ["local-offset"]}
tinyvec = {version = "1", features = ["alloc"]}
unicode-segmentation = "1.10"

[features]

[lib]
crate-type = ["cdylib"]

[workspace]
#members = ["site", "tests_ffi", "pad/editor"]

[profile.release]
lto = true
opt-level = "z"

[profile.dev]
incremental = true
